services:

  database:
    image: postgres:17
    container_name: database_alcorti
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - alcorti_storage:/var/lib/postgresql/data
    networks:
      - alcorti_network

  alcorti_api :
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - alcorti_network

networks:
  alcorti_network:
    driver: bridge

volumes:
  alcorti_storage:
    driver: local