services:

  database:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - alcorti_network

  api :
    container_name: alcorti_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - alcorti_network

networks:
  alcorti_network:
    driver: bridge

volumes:
  postgres:
    driver: local